import "../styles/globals.css";
import Header from "./Header";

export const metadata = {
    title: "Meta Messenger Clone",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                {/* @ts-expect-error Server Component */}
                <Header />
                {children}
            </body>
        </html>
    );
}
